name: Deployment to Staging
on:
  push:
    branches: [main]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying Everything to Staging
    steps: 
      - name: Deploy to staging server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 52.66.213.64
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd development/
            git pull
            pnpm install
            pnpm run build
            pm2 restart fe-server
            pm2 restart http-server
            pm2 restart ws-server