name: Deployment to Staging
on:
  push:
    branches: [main]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying Everything to Staging
    steps: 
      - name: Deploy to staging server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@52.66.213.64 << 'EOF'
          cd development/
          git pull
          pnpm install
          pnpm run build
          pm2 restart fe-server
          pm2 restart http-server
          pm2 restart ws-server
          EOF