name: CD to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=yes -i ~/ssh_key ubuntu@3.110.159.132 "
            cd development/ &&
            git pull origin main &&
            export NVM_DIR=\"\$HOME/.nvm\" &&
            [ -s \"\$NVM_DIR/nvm.sh\" ] && source \"\$NVM_DIR/nvm.sh\" &&
            nvm use 22.13.1 &&
            npm install -g pnpm &&
            export PATH=\"\$PATH:\$(npm config get prefix)/bin\" &&
            pnpm install &&
            pnpm run build &&
            pm2 restart fe-server --update-env &&
            pm2 restart http-server --update-env &&
            pm2 restart ws-server --update-env
          "