---
name: Deploy to staging
on:
  push:
    branches:
      - main
jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster
    steps:
      - run: >
          # Create SSH directory and set proper permissions

          mkdir -p ~/.ssh

          chmod 700 ~/.ssh


          # Write SSH private key with proper permissions

          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

          chmod 600 ~/.ssh/id_rsa


          # Write known hosts

          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

          chmod 644 ~/.ssh/known_hosts


          # Test SSH connection first

          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@13.201.42.65 "echo 'SSH connection successful'"


          # Deploy

          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@13.201.42.65 << 'EOF'
            cd week-25-ci-next-app/
            git pull origin main
            export PATH=/root/.nvm/versions/node/v22.13.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
            npm install -g pnpm
            pnpm install
            pnpm run build
            pm2 restart fe-sever
            pm2 restart http-sever
            pm2 restart ws-sever
