name: Deploy to staging

on:
  push:
    branches: [ main ]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster
    steps:
      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

          ssh -o StrictHostKeyChecking=yes -i ~/ssh_key ubuntu@13.201.42.65 -t "
            cd ~/development/week-25-ci-next-app/ &&
            git pull origin main &&
            export PATH=/home/ubuntu/.nvm/versions/node/v22.19.0/bin:\$PATH &&
            npm install -g pnpm &&
            pnpm install &&
            pnpm run build &&
            pm2 restart fe-sever &&
            pm2 restart http-sever &&
            pm2 restart ws-sever
          "
