name: CD to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=yes -i ~/ssh_key ubuntu@3.110.159.132 -t "
            cd development/ &&
            git pull origin main &&
            export PATH=/home/ubuntu/.nvm/versions/node/v22.13.1/bin:/usr/local/bin:/usr/bin:/bin &&
            npm install -g pnpm || true &&
            pnpm install &&
            pnpm run build &&
            pm2 restart fe-server &&
            pm2 restart http-server &&
            pm2 restart ws-server
          "
